# 반복
* ndarray를 반복하는 것은 일반적인 파이썬 배열을 반복하는 것과 매우 유사하다. 다차원 배열을 반복하면 첫 번재 축에 대해서 수행된다.

In [1]:
import numpy as np
c = np.arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [2]:
for m in c:
    print("item:")
    print(m)

item:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
item:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [3]:
for i in range(len(c)):
    print("item: ")
    print(c[i])

item: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
item: 
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


* ndarray에 있는 모든 원소를 반복하려면 flat 속성을 사용한다.

In [4]:
for i in c.flat:
    print("item:", i)

item: 0
item: 1
item: 2
item: 3
item: 4
item: 5
item: 6
item: 7
item: 8
item: 9
item: 10
item: 11
item: 12
item: 13
item: 14
item: 15
item: 16
item: 17
item: 18
item: 19
item: 20
item: 21
item: 22
item: 23


# 배열 쌓기
* 종종 다른 배열을 쌓아야 할 때가 있다. 이를 위해 몇 개의 함수를 제공한다.

In [6]:
q1 = np.full((3,4), 1.0)
q1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
q2 = np.full((4,4), 2.0)
q2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [9]:
q3 = np.full((3,4), 3.0)
q3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

* vstack: 수직으로 쌓는 함수

In [10]:
q4 = np.vstack((q1, q2, q3))
q4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [12]:
q4.shape

(10, 4)

* hstack: 수평으로 쌓는 함수

In [15]:
q5 = np.hstack((q1, q3))
q5

array([[1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.]])

In [16]:
q5.shape

(3, 8)

In [20]:
q7 = np.concatenate((q1, q2, q3), axis=0)
q7

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [21]:
q7.shape

(10, 4)

* stack: 새로운 축을 따라 배열을 쌓는다. 모든 배열은 같은 크기를 가져야 한다.

In [26]:
xq = np.full((3, 4), 4.0)
q8 = np.stack((q1, q3, xq))
q8

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]])

In [27]:
q8.shape

(3, 3, 4)