In [1]:
import numpy as np

# 선형 대수학
* NumPy 2D 배열을 사용하면 파이썬에서 행렬을 효율적으로 표현할 수 있다.

# 행렬 전치
* T 속성은 rank가 2보다 크거나 같을 때 transpose()를 호출하는 것과 같다.
* transpose() 함수는 차원의 순서를 역전시킨다 (0,1,2) -> (2,1,0)

In [3]:
m1 = np.arange(10).reshape(2,5)
m1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
m1.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

* T 속성은 rank가 0이거나 1인 배열에는 아무런 영향이 없다.

In [5]:
m2 = np.arange(5)
m2

array([0, 1, 2, 3, 4])

In [6]:
m2.T

array([0, 1, 2, 3, 4])

In [7]:
m2r = m2.reshape(1,5)
m2r

array([[0, 1, 2, 3, 4]])

In [8]:
m2r.T

array([[0],
       [1],
       [2],
       [3],
       [4]])

# 행렬 점곱
* 두 개의 행렬을 만들어 dot 메서드로 행렬 점곱을 실행한다.

In [9]:
n1 = np.arange(10).reshape(2,5)
n1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
n2 = np.arange(15).reshape(5,3)
n2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [11]:
n1.dot(n2)

array([[ 90, 100, 110],
       [240, 275, 310]])

# 역행렬과 유사 역행렬
numpy.linalg 모듈 안에 많은 선형 대수 함수들이 있다. 특히 inv 함수는 정방 행렬의 역행렬을 계산한다.

In [12]:
import numpy.linalg as linalg

m3 = np.array([[1,2,3],[5,7,11],[21,29,31]])
m3

array([[ 1,  2,  3],
       [ 5,  7, 11],
       [21, 29, 31]])

In [13]:
linalg.inv(m3)

array([[-2.31818182,  0.56818182,  0.02272727],
       [ 1.72727273, -0.72727273,  0.09090909],
       [-0.04545455,  0.29545455, -0.06818182]])

* pinv 함수는 유사 역행렬을 계산

In [14]:
linalg.pinv(m3)

array([[-2.31818182,  0.56818182,  0.02272727],
       [ 1.72727273, -0.72727273,  0.09090909],
       [-0.04545455,  0.29545455, -0.06818182]])

# 단위 행렬
* 행렬과 그 행렬의 역행렬을 곱하면 단위 행렬이 된다.

In [15]:
m3.dot(linalg.inv(m3))

array([[ 1.00000000e+00, -1.66533454e-16,  0.00000000e+00],
       [ 6.31439345e-16,  1.00000000e+00, -1.38777878e-16],
       [ 5.21110932e-15, -2.38697950e-15,  1.00000000e+00]])

* eye 함수는 NxN 크기의 단위 행렬을 만든다.

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])