In [1]:
import numpy as np

In [6]:
a = np.array([14, 23, -32, 41])
b = np.array([5, -4, 3, 2])

In [7]:
np.maximum(a, b)

array([14, 23,  3, 41])

In [10]:
np.copysign(a, b)

array([ 14., -23.,  32.,  41.])

# 배열 인덱싱

In [11]:
a = np.array([1, 5, 3, 19, 13, 7, 3])
a[3]

19

In [12]:
a[2:5]

array([ 3, 19, 13])

In [13]:
a[2:-1]

array([ 3, 19, 13,  7])

In [14]:
a[:2]

array([1, 5])

In [15]:
a[2::2]

array([ 3, 13,  3])

In [16]:
a[::-1]

array([ 3,  7, 13, 19,  3,  5,  1])

In [17]:
a[3] =  999
a

array([  1,   5,   3, 999,  13,   7,   3])

In [18]:
a[2:5] = [997, 998, 999]
a

array([  1,   5, 997, 998, 999,   7,   3])

* 보통의 파이썬 배열과 대조적으로  ndarray 슬라이싱에 하나의 값을 할당하면 브로드 캐스팅으로 인해 슬라이싱 전체에 복사된다.

In [20]:
a_slice = a[2:6]
a_slice[1] = 1000
a

array([   1,    5,  997, 1000,  999,    7,    3])

* 브로드 캐스팅으로 인해 원본 ndarray의 복사를 방지하려면 copy 메서드 사용

In [21]:
another_slice = a[2:6].copy()
another_slice[1] = 1101
a

array([   1,    5,  997, 1000,  999,    7,    3])

# 다차원 배열

In [22]:
b = np.arange(48).reshape(4,12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [23]:
b[1,2]

14

In [24]:
b[1, :]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [25]:
b[:, 1]

array([ 1, 13, 25, 37])

In [26]:
b[1, :]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [27]:
b[1:2, :]

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

* 두 표현식에는 차이가 있는데, 첫 번째 b[1, :]는 (12,)크기인 1D 배열로 행이 1개이다. 두 번째는 (1, 12)크기인 2D 배열로 같은 행을 반환한다.

In [28]:
b[:,1:2]

array([[ 1],
       [13],
       [25],
       [37]])

# Fancy Indexing
* 관심 대상의 인덱스 리스트를 지정할 수도 있다.

In [29]:
b[(0,2), 2:5]

array([[ 2,  3,  4],
       [26, 27, 28]])

In [30]:
b[0:2, 2:5]

array([[ 2,  3,  4],
       [14, 15, 16]])

In [31]:
b[:, (-1, 2, -1)]

array([[11,  2, 11],
       [23, 14, 23],
       [35, 26, 35],
       [47, 38, 47]])

In [32]:
b[(-1, 2, -1, 2), (5, 9, 1, 9)]

array([41, 33, 37, 33])

# 고차원

In [34]:
c = b.reshape(4, 2, 6)
c

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

In [35]:
c[2, 1, 4]

34

In [36]:
c[2, : ,3]

array([27, 33])

# 생략 부호(...)

In [37]:
c[2, 1, ...]

array([30, 31, 32, 33, 34, 35])

In [38]:
c[2, ..., 3]

array([27, 33])

In [40]:
c[..., 3]

array([[ 3,  9],
       [15, 21],
       [27, 33],
       [39, 45]])

# Boolean Indexing

In [41]:
b = np.arange(48).reshape(4, 12)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [43]:
rows_on = np.array([True, False, True, False])
b[rows_on, :] # 행 0과 2, 모든 열. b[(0, 2), :]와 동일

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [44]:
cols_on = np.array([False, True, False] * 4)
b[:, cols_on]

array([[ 1,  4,  7, 10],
       [13, 16, 19, 22],
       [25, 28, 31, 34],
       [37, 40, 43, 46]])

* np.ix_: 여러 축에 걸쳐서는 Boolean indexing을 사용할 수 없고, ix_ 함수를 사용한다.

In [45]:
b[np.ix_(rows_on, cols_on)]

array([[ 1,  4,  7, 10],
       [25, 28, 31, 34]])

In [46]:
np.ix_(rows_on, cols_on)

(array([[0],
        [2]]),
 array([[ 1,  4,  7, 10]]))

In [47]:
b[b % 3 == 1]

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46])