In [1]:
import numpy as np

# 배열 분할
* 분할은 쌓기의 반대이다. 예를 들어 vsplit 함수는 행렬을 수직으로 분할한다.

In [3]:
# 6x4 matrix
r = np.arange(24).reshape(6,4)
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
# 수직으로 동일한 크기로 나누기
r1, r2, r3 = np.vsplit(r, 3)
print(r1)
print(r2)
print(r3)

v1, v2 = np.vsplit(r, 2)
print(v1)
print(v2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


* split 함수는 주어진 축을 따라 배열을 분할한다.
* vsplit 함수는 axis=0으로 split을 호출하는 것과 같다.
* hsplit 함수는 axis=1로 split을 호출하는 것과 같다.

In [7]:
r4, r5 = np.hsplit(r, 2)
print(r4)
print(r5)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]
 [20 21]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]
 [22 23]]


# 배열 전치
* transpose 메서드는 주어진 순서대로 축을 뒤바꾸어 ndarray 데이터에 대한 새로운 view를 만든다.

In [13]:
# 3D array 생성
t = np.arange(24).reshape(4,2,3)
t

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

* 0, 1, 2(깊이, 높이, 너비) 축을 2, 0, 1(깊이->너비, 높이->깊이, 너비->높이) 순서로 바꾼 ndarray를 만든다.

In [21]:
t1 = t.transpose((2,0,1)) # 3 4 2
t1

array([[[ 0,  3],
        [ 6,  9],
        [12, 15],
        [18, 21]],

       [[ 1,  4],
        [ 7, 10],
        [13, 16],
        [19, 22]],

       [[ 2,  5],
        [ 8, 11],
        [14, 17],
        [20, 23]]])

In [24]:
t1.shape

(3, 4, 2)

* transpose 기본값은 차원의 순서를 역전시킨다.(0, 1, 2) -> (2, 1, 0)

In [25]:
t2 = t.transpose() 
t2

array([[[ 0,  6, 12, 18],
        [ 3,  9, 15, 21]],

       [[ 1,  7, 13, 19],
        [ 4, 10, 16, 22]],

       [[ 2,  8, 14, 20],
        [ 5, 11, 17, 23]]])

In [26]:
t2.shape

(3, 2, 4)

* NumPy는 두 축을 바꾸는 swapaxes 함수를 제공한다.

In [29]:
t3 = t.swapaxes(0,2) # t.transpose((2,1,0))와 동일 4 2 3 -> 3 2 4 
t3

array([[[ 0,  6, 12, 18],
        [ 3,  9, 15, 21]],

       [[ 1,  7, 13, 19],
        [ 4, 10, 16, 22]],

       [[ 2,  8, 14, 20],
        [ 5, 11, 17, 23]]])

In [30]:
t3.shape

(3, 2, 4)