# np.fromfunction

* 함수를 사용하여 ndarray를 초기화할 수도 있다.

In [5]:
import numpy as np
def my_function(z, y, x):
    return x*y+z

# 3차원 2x10
np.fromfunction(my_function, (3, 2, 10))

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]],

       [[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]],

       [[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
        [ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]]])

* numpy는 먼저 크기가(3, 2, 10)인 세 개의 ndarray(차원마다 하나씩)를 만든다

# Array Data

# dtype

* NumPy의 ndarray는 모든 원소가 동일한 타입을 가지기 때문에 효율적이다.

In [6]:
c = np.arange(1, 5)
print(c.dtype, c)

int64 [1 2 3 4]


In [7]:
c = np.arange(1.0, 5.0)
print(c.dtype, c)

float64 [1. 2. 3. 4.]


In [8]:
d = np.arange(1, 5, dtype=np.complex64)
print(d.dtype, d)

complex64 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


# itemsize

* itemsize 속성은 각 item의 크기(byte)를 반환한다.

In [10]:
e = np.arange(1, 5, dtype=np.complex64)
print(e.dtype, e)
print(e.itemsize)

complex64 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]
8


# Data 버퍼

* 배열의 데이터는 1차원 바이트 버퍼로 메모리에 저장된다. data 속성을 사용해 참조할 수 있다.

In [11]:
f = np.array([[1,2], [1000, 2000]], dtype=np.int32)
f.data

In [12]:
if(hasattr(f.data, "tobytes")):
    data_bytes = f.data.tobytes()
else:
    data_bytes = memoryview(f.data).tobytes()

data_bytes

b'\x01\x00\x00\x00\x02\x00\x00\x00\xe8\x03\x00\x00\xd0\x07\x00\x00'

# 배열 크기 변경

In [13]:
# 자신을 변경

g = np.arange(24)
print(g)
print(f"rank: {g.ndim}")

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
rank: 1


In [14]:
g.shape = (6, 4)
print(g)
print(f"rank: {g.ndim}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
rank: 2


In [17]:
g.shape = (2, 3, 4)
print(g)
print(f"rank: {g.ndim}")

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
rank: 3


# reshape

* reshape 함수는 동일한 데이터를 가리키는 새로운 ndarray 객체를 반환한다. 한 배열을 수정하면 다른 것도 함께 바뀐다.

In [18]:
g2 = g.reshape(4, 6)
print(g2)
print(f"rank: {g2.ndim}")

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
rank: 2


In [19]:
g2[1, 2] = 999
g2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7, 999,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

In [20]:
g

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [999,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

# ravel

* revel 함수는 동일한 데이터를 가리키는 새로운 1차원 ndarray를 반환한다.

In [21]:
g.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7, 999,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])