In [1]:
import numpy as np

# 산술연산

* 그러나 곱셈은 행렬의 곱셈이 아니라 그냥 원소끼리의 연산이다.

In [4]:
a = np.array([14, 23, 32, 41])
b = np.array([5, 4, 3, 2])
print(f"a + b = {a+b}")
print(f"a - b = {a-b}")
print(f"a * b = {a*b}")
print(f"a / b = {a/b}")
print(f"a // b = {a//b}")
print(f"a % b = {a%b}")
print(f"a ** b = {a**b}")

a + b = [19 27 35 43]
a - b = [ 9 19 29 39]
a * b = [70 92 96 82]
a / b = [ 2.8         5.75       10.66666667 20.5       ]
a // b = [ 2  5 10 20]
a % b = [4 3 2 1]
a ** b = [537824 279841  32768   1681]


# Broadcasting

* 일반적으로 NumPy는 동일한 크기의 배열을 기대한다. 그렇지 않은 상황에는 broadcasing 규칙을 적용한다.

# Rule 1

* 배열의 rank가 동일하지 않으면 rank가 맞을 때까지 작은 rank가 작은 배열 앞에 1을 추가한다.

In [5]:
h = np.arange(5).reshape(1, 1, 5)
h

array([[[0, 1, 2, 3, 4]]])

* 여기에 (1,1,5) 크기의 3D 배열에 (5,) 크기의 1D 배열을 더해본다.

In [6]:
h + [10, 20, 30, 40, 50]

array([[[10, 21, 32, 43, 54]]])

# Rule 2

* 특정 차원이 1인 배열은 그 차원에서 크기가가장 큰 배열의 크기에 맞춰 동작한다. 배열의 원소가 작은 차원을 따라 반복된다.

In [7]:
k = np.arange(6).reshape(2, 3)
k

array([[0, 1, 2],
       [3, 4, 5]])

* (2,3)크기의 2D ndarray에 (2,1)크기의 2D 배열을 더해 본다.

In [8]:
k + [[100], [200]]

array([[100, 101, 102],
       [203, 204, 205]])

In [9]:
# 규칙 1과 규칙 2를 적용
k + [100, 200, 300]

array([[100, 201, 302],
       [103, 204, 305]])

# Rule 3

* 규칙 1과 2를 적용했을 때, 모든 배열의 크기가 맞아야 한다.

In [16]:
try:
    k + [33, 44]
except ValueError as e:
    print(e)
k + [33, 44, 55]

operands could not be broadcast together with shapes (2,3) (2,) 


array([[33, 45, 57],
       [36, 48, 60]])

# Upcasting

* dtype이 다른 배열을 합칠 때 NumPy는 (실제 값에 상관없이) 모든 값을 다룰 수 있는 타입으로 upcasting

In [18]:
k1 = np.arange(0, 5, dtype=np.uint8)
print(k1.dtype, k1)

uint8 [0 1 2 3 4]


In [19]:
k2 = k1 + np.array([5, 6, 7, 8, 9], dtype=np.int8)
print(k2.dtype, k2)

int16 [ 5  7  9 11 13]


In [20]:
k3 = k1 + 1.5
print(k3.dtype, k3)

float64 [1.5 2.5 3.5 4.5 5.5]
