In [1]:
import math
import random
import tensorflow as tf

2023-11-21 16:00:59.071190: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [44]:
active_clients = 4
num_layers = 3
alpa = 1

In [45]:
mutated_model = [[0 for _ in range(num_layers)] for _ in range(active_clients)]
print(mutated_model)

[[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]


In [46]:
# random vector 생성
layer = [-1] * (math.floor(active_clients//2)) + [1] * (math.floor(active_clients//2))
L_layers = [layer[:] for _ in range(num_layers)]
print("random vector: ",L_layers)

random vector:  [[-1, -1, 1, 1], [-1, -1, 1, 1], [-1, -1, 1, 1]]


In [47]:
for i in range(num_layers):
        random.shuffle(L_layers[i])

print("shuffled random vector: ",L_layers)

print("shuffled random vector")
for i in range(num_layers):
        print(L_layers[i])
        

shuffled random vector:  [[-1, 1, 1, -1], [1, -1, 1, -1], [-1, -1, 1, 1]]
shuffled random vector
[-1, 1, 1, -1]
[1, -1, 1, -1]
[-1, -1, 1, 1]


In [97]:
# 3x3x4x4
weights_delta = [
    [
        [ # 첫 번째 3x4x4 텐서
            [   
                # 첫 번재 4x4 matrix
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ],
            [
                # 두 번재 4x4 matrix   
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ],
            [
                # 세 번재 4x4 matrix
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ]
                        
        ],
        [
            [
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ],
            [
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ],
            [
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ]
        ],
        [
            [
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ],
            [
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ],
            [
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ]
        ],
    ],
    [
        [ # 첫 번째 3x4x4 텐서
            [   
                # 첫 번재 4x4 matrix
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ],
            [
                # 두 번재 4x4 matrix   
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ],
            [
                # 세 번재 4x4 matrix
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ]
                        
        ],
        [
            [
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ],
            [
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ],
            [
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ]
        ],
        [
            [
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ],
            [
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ],
            [
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ]
        ],
    ],[
        [ # 첫 번째 3x4x4 텐서
            [   
                # 첫 번재 4x4 matrix
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ],
            [
                # 두 번재 4x4 matrix   
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ],
            [
                # 세 번재 4x4 matrix
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ]
                        
        ],
        [
            [
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ],
            [
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ],
            [
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ]
        ],
        [
            [
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ],
            [
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ],
            [
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ]
        ],
    ]
]

# 3, 3x3x4x4
global_weights = [
    [
        [ # 첫 번째 3x4x4 텐서
            [   
                # 첫 번재 4x4 matrix
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ],
            [
                # 두 번재 4x4 matrix   
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ],
            [
                # 세 번재 4x4 matrix
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ]
                        
        ],
        [
            [
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ],
            [
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ],
            [
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ]
        ],
        [
            [
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ],
            [
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ],
            [
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ]
        ],
    ],
    [
        [ # 첫 번째 3x4x4 텐서
            [   
                # 첫 번재 4x4 matrix
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ],
            [
                # 두 번재 4x4 matrix   
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ],
            [
                # 세 번재 4x4 matrix
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ]
                        
        ],
        [
            [
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ],
            [
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ],
            [
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ]
        ],
        [
            [
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ],
            [
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ],
            [
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ]
        ],
    ],
    [
        [ # 첫 번째 3x4x4 텐서
            [   
                # 첫 번재 4x4 matrix
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ],
            [
                # 두 번재 4x4 matrix   
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ],
            [
                # 세 번재 4x4 matrix
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ]
                        
        ],
        [
            [
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ],
            [
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ],
            [
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ]
        ],
        [
            [
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3],
                [0.3, 0.3, 0.3, 0.3]
            ],
            [
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1],
                [0.1, 0.1, 0.1, 0.1]
            ],
            [
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2],
                [0.2, 0.2, 0.2, 0.2]
            ]
        ],
    ]
]


In [98]:
print(weights_delta[0])
print(weights_delta[1])
print(weights_delta[2])

print(global_weights[0])
print(global_weights[1])
print(global_weights[2])

weights_delta_tensor = tf.constant(weights_delta)
global_weights_tensor = tf.constant(global_weights)

print(weights_delta_tensor[0].shape)
print(weights_delta_tensor[1].shape)
print(weights_delta_tensor[2].shape)

print(global_weights_tensor[0].shape)
print(global_weights_tensor[1].shape)
print(global_weights_tensor[2].shape)

print(type(weights_delta_tensor))
print(type(global_weights_tensor))


[[[[0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1]], [[0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2]], [[0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3]]], [[[0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2]], [[0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1]], [[0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3]]], [[[0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1]], [[0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2]], [[0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3]]]]
[[[[0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1]], [[0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2]], [

* tf.constant() 함수는 list를 Tensor로 변환하는 함수다. 이때, 변환하려고 하는 list의 모든 내부 요소들이 동일한 차원과 형태를 가져야 한다.

* 해결 방법은 변환하려고 하는 list의 모든 요소를 tf.Tensor 객체의 list로 변환할 수 있다. 이렇게 한다면 각 요소를 TensorFlow의 연산에 사용할 수 있으며, list 형태로 유지된다. 

In [93]:
for i in range(2* math.floor(active_clients//2)): # 0 1 2 3
        mutated_weights = global_weights

        for j in range(num_layers): # 0 1 2
                mutation_value = alpa * L_layers[j][i] * weights_delta_tensor[j]
                if i == 0:
                        print("alpa: {}".format(alpa))
                        print("L_layer[{}][{}]: {}".format(j,i,L_layers[j][i]))
                        print("weights_delta[{}]: {}".format(j, weights_delta[j]))
                        print("mutation_value: {}".format(mutation_value))
                        print("global_weights[{}]: {}".format(j, global_weights_tensor[j]))
                
                mutated_weights[j] = (global_weights_tensor[j] + mutation_value)
                if i == 0:
                        print("parameter of client {}'s {} layer: {}".format(i, j, mutated_weights[j]))
                                
                mutated_model[i][j] = mutated_weights[j]


'''
shuffled random vector:  [[-1, 1, 1, -1], [1, -1, 1, -1], [-1, -1, 1, 1]]

'''

alpa: 1
L_layer[0][0]: -1
weights_delta[0]: [[[[0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1]], [[0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2]], [[0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3]]], [[[0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2]], [[0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1]], [[0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3]]], [[[0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1], [0.1, 0.1, 0.1, 0.1]], [[0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2], [0.2, 0.2, 0.2, 0.2]], [[0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3], [0.3, 0.3, 0.3, 0.3]]]]
mutation_value: [[[[-0.1 -0.1 -0.1 -0.1]
   [-0.1 -0.1 -0.1 -0.1]
   [-0.1 -0.1 -0.1 -0.1]
   [-0.1 -0.1 -0.1 -0.1]]

  [[-0.2 -0.2 -0.2 -0

'\nshuffled random vector:  [[-1, 1, 1, -1], [1, -1, 1, -1], [-1, -1, 1, 1]]\n\nPython에서 리스트와 스칼라 값을 곱하면, 리스트의 내용이 스칼라 값만큼 반복된다.\n이때, 음수가 리스트에 곱해지면 []를 반환한다.\n'

* Python에서 리스트와 스칼라 값을 곱하면, 리스트의 내용이 스칼라 값만큼 반복된다.
  이때, 음수가 리스트에 곱해지면 []를 반환한다.

* TensorFlow는 내부적으로 부동 소수점 연산을 사용한다.

* TensorFlow의 Tensor 자료형은 기본적으로 부동 소수점 자료형인 tf.float32를 사용한다. 따라서, 0.3과 0.1을 더하거나 빼는 연산에서 0.2대신 0.200000002와 같은 결과가 나올 수 있다.

In [85]:
print(mutated_model)
print(len(mutated_model))


[[<tf.Tensor: shape=(3, 3, 4, 4), dtype=float32, numpy=
array([[[[ 0.20000002,  0.20000002,  0.20000002,  0.20000002],
         [ 0.20000002,  0.20000002,  0.20000002,  0.20000002],
         [ 0.20000002,  0.20000002,  0.20000002,  0.20000002],
         [ 0.20000002,  0.20000002,  0.20000002,  0.20000002]],

        [[-0.1       , -0.1       , -0.1       , -0.1       ],
         [-0.1       , -0.1       , -0.1       , -0.1       ],
         [-0.1       , -0.1       , -0.1       , -0.1       ],
         [-0.1       , -0.1       , -0.1       , -0.1       ]],

        [[-0.10000001, -0.10000001, -0.10000001, -0.10000001],
         [-0.10000001, -0.10000001, -0.10000001, -0.10000001],
         [-0.10000001, -0.10000001, -0.10000001, -0.10000001],
         [-0.10000001, -0.10000001, -0.10000001, -0.10000001]]],


       [[[ 0.10000001,  0.10000001,  0.10000001,  0.10000001],
         [ 0.10000001,  0.10000001,  0.10000001,  0.10000001],
         [ 0.10000001,  0.10000001,  0.10000001,  0.10