In [12]:
import tensorflow as tf
import numpy as np

* Tensorflow 란

Tensorflow는 머신 러닝 및 인공 지능을 위한 오픈 소스 소프트웨어 라이브러리이다.
데이터 플로우 그래프(Data Flow Graph) 방식을 사용한다.

* 데이터 플로우 그래프(Data Flow Graph)란
데이터 플로우 그래프는 수학 계산과 데이터의 흐름을 Node와 Edge를 사용한 Directed Graph로 표현한다.
Node는 수학적 계산, 입/출력(I/O), 그리고 데이터의 읽기/저장 등의 작업을 수행한다.
Edge는 Node들 간 데이터의 입출력 관계를 나타낸다.
Edge는 Tensor(다차원 데이터 배열)을 실어 나르는데, 이것이 곧 Tensorflow이다.

* Tensor란?
인공지능에서의 Tensor은 수학적 개념의 다차원 배열(N-Dimentional array)이다.
Tensor을 이해하기 위해 Rank, Shape, Type을 알아야 한다.

* Rank
Tensor의 차원을 의미한다.
Rank    Type
0       Scalar
1       Vector
2       Matrix
3       3 Tensor
4       4 Tensor

* Shape
각 축(axis)이 몇개의 Element로 구성되어있는지 나타내는 값이다.
차원과 함께 몇개의 원소들로 이루어져 있는지의 여부를 파악 가능하다.

* Type
Data Type       Python Type     Description
DT_FLOAT        tf.float32      32 bits floating point
DT_DOUBLE       tf.float64      64 bits floating point
DT_INT8         tf.int8         8 bits signed integer
DT_INT16        tf.int16        16 bits signed integer
DT_INT32        tf.int32        32 bits signed integer
DT_INT64        tf.int64        64 bits signed integer

In [17]:
# Tensor의 생성
# Python의 NumPy를 통해 생성한 array/tuple/list는 Tensorflow의 tf.constant()함수를 통해 Tensor로 변환할 수 있다.
arr = np.array((1,2,3))
print(tf.constant(arr))


tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [21]:
arr = np.ones((3,4))
print(tf.constant(arr))

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float64)


In [41]:
# tensor 생성시에 data type을 정의할 수 있다.
tensor = tf.constant([1,2,3], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [43]:
arr = np.full((4,5,2), 3.11215498)
tensor = tf.constant(arr)
tensor

<tf.Tensor: shape=(4, 5, 2), dtype=float64, numpy=
array([[[3.11215498, 3.11215498],
        [3.11215498, 3.11215498],
        [3.11215498, 3.11215498],
        [3.11215498, 3.11215498],
        [3.11215498, 3.11215498]],

       [[3.11215498, 3.11215498],
        [3.11215498, 3.11215498],
        [3.11215498, 3.11215498],
        [3.11215498, 3.11215498],
        [3.11215498, 3.11215498]],

       [[3.11215498, 3.11215498],
        [3.11215498, 3.11215498],
        [3.11215498, 3.11215498],
        [3.11215498, 3.11215498],
        [3.11215498, 3.11215498]],

       [[3.11215498, 3.11215498],
        [3.11215498, 3.11215498],
        [3.11215498, 3.11215498],
        [3.11215498, 3.11215498],
        [3.11215498, 3.11215498]]])>

In [44]:
# tensor.shape 함수는 Tensor의 shape을 확인한다.
tensor.shape

TensorShape([4, 5, 2])

In [45]:
# tf.shape 함수는 Tensor의 shape을 확인한다. 이 함수는 주어진 tensor의 구조, 즉 각 차원의 요소 수를 이해하는데 유용하다
tf.shape(tensor)

# tensor 자체는 1차원이고 (3,), 그 길이는 3이다. 이 3개의 요소는 원래 tensor의 각 차원의 크기이다.
# dtype=int32는 이 tensor가 int형 data를 갖고 있음을 나타낸다. 여기서 데이터는 tensor의 각 차원의 크기이다. 여기서는 4,5,2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 2], dtype=int32)>

* tensor.shape와 tf.shape의 차이점

1. tensor.shape
- tensor.shape은 tensor의 '정적 형태'를 반환한다. 이는 tensor가 생성될 때 결정되며, 코드가 실행되지 전에 알 수 있는 형태이다.
- 정적 형태는 tensor의 구조가 고정되어 있고 변경되지 않는 경우에 사용된다. 이 형태는 Python의 tuple형태로 반환된다.

2. tf.shape(tensor)
- tf.shape(tensor)은 tensor의 '동적 형태'를 반환한다. 이는 run time에 결정되며, tensor의 형태가 실행 중에 변경될 수 있는 경우에 유용하다.
- 동적 형태는 run time에 계산되며, tensor 자체로 반환된다. 이는 tensor의 차원이 프로그램을 실행 도중에 변경될 수 있을 때 필요하다.

In [46]:
# tensor.dtype 함수는 tensor의 data type을 확인한다.
tensor.dtype

tf.float64

In [47]:
# tf.cast 함수는 data type, 즉, dtype을 변환해줄 수 있다.
tf.cast(tensor, dtype=tf.uint8)

<tf.Tensor: shape=(4, 5, 2), dtype=uint8, numpy=
array([[[3, 3],
        [3, 3],
        [3, 3],
        [3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3],
        [3, 3],
        [3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3],
        [3, 3],
        [3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3],
        [3, 3],
        [3, 3],
        [3, 3]]], dtype=uint8)>