# Get Tensorflow

In [1]:
import tensorflow as tf

2023-12-18 10:36:56.038753: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-18 10:36:56.367628: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


# Tensor  

* tensor은 다차원 배열이다. NumPy ndarray 객체와 유사하게 tf.Tensor 객체에는 데이터 유형과 형상이 있다. 또한 tf.Tensor는 GPU에서 계산된다.
* tensorflow는 tf.Tensor의 연산을 위한 다양한 library를 제공한다.

In [4]:
print(tf.math.add(1, 2))
print(tf.math.add([1, 2], [3, 4]))
print(tf.math.square(5))
print(tf.math.reduce_sum([1, 2, 3]))


# Operator overloading is also supported
print(tf.math.square(2) + tf.math.square(3))


tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


In [6]:
x = tf.linalg.matmul([[1]], [[2, 3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


# NumPy 배열과 tf.Tensor의 차이
1. Tensor는 GPU, TPU와 같은 accelerator memory에서 사용가능하다.
2. tensor는 immutable(불변성)을 가진다.

* tensor는  .numpy() 메서드를 호출하여 NumPy 배열로 변환할 수 있다. 가능한 경우, tf.Tensor와 배열은 메모리 표현을 공유하기 때문에 이러한 변환은 cost가 저렴하다. 그러나 tf.Tensor는 GPU Memory에 저장될 수 있고, NumPy 배열은 Host Memory에 저장되므로, 변환이 항상 가능한 것은 아니다. 따라서 GPU에서 Host Memory로 복사가 필요하다.

In [2]:
import numpy as np

ndarray = np.ones([3, 3])

print("Tensorflow operations convert numpy arrays to Tensors automatically")
tensor = tf.math.multiply(ndarray, 42)
print(tensor)

print("And NumPy operations convert Tensors to NumPy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())

Tensorflow operations convert numpy arrays to Tensors automatically


2023-12-18 10:37:30.421114: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-12-18 10:37:30.429666: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-12-18 10:37:30.429738: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-12-18 10:37:30.432378: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And NumPy operations convert Tensors to NumPy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


ut NUMA support.
2023-12-18 10:37:30.435891: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-12-18 10:37:30.435920: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-12-18 10:37:31.425716: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-12-18 10:37:31.425853: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:966] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-12-18 10:37:31.425867: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1700

# GPU accelerate

* 대부분의 TensorFlow 연산은 GPU를 사용하여 가속화된다. 어떠한 코드를 명시하지 않아도, TensorFlow는 연산을 위해 CPU 또는 GPU를 사용할 것인지를 자동으로 결정한다. 필요 시 Tensor를 CPU와 GPU Memory 사이에서 복사한다. 연산에 의해 생성된 tensor는 전형적으로 연산이 실행된 장치의 Memory에 의해 실행된다.

In [3]:
x = tf.random.uniform([3, 3])

print("Is there a GPU available: "),
print(tf.config.list_logical_devices("GPU"))

print("Is the Tensor on GPU #0: "),
print(x.device.endswith('GPU:0'))


Is there a GPU available: 
[LogicalDevice(name='/device:GPU:0', device_type='GPU')]
Is the Tensor on GPU #0: 
True


# Explicit device placement

* TensorFlow에서 batch는 개별 연산이 실행을 위해 장치에 할당(batch)되는 방식을 나타낸다. 언급했듯이 명시적인 지침이 제공되지 않으면 TensorFlow는 연산을 실행할 장치를 자동으로 결정하고 필요한 경우 해당 장치에 Tensor를 복사한다.

* 그러나 TensorFlow 연산은 tf.device 컨텍스트 관리자를 사용하여 특정 장치에 명시적으로 배치할 수 있다

In [ ]:
import time

def time_matmul(x):
    start = time.time()
    for loop in range(10):
        tf.linalg.matmul(x, x)

    result = time.time()-start
    print("10 loops: {:0.2f}ms".format(1000*result))

# Force execution on CPU
print("On CPU:")
with tf.device("CPU:0"):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("CPU:0")
    time_matmul(x)

# Force execution on GPU #0 if available
if tf.config.list_physical_devices("GPU"):
    print("On GPT:")
    with tf.device("GPU:0"): # Or GPU:1 for the 2nd GPU, GPU:2 for the 3rd etc.
        x = tf.random.uniform([1000, 1000])
        assert x.device.endswith("GPU:0")
        time_matmul(x)


        